algorithm : dreamer-v3
operation :
    save : False
    log_dir : multicar
    device : cuda
environment :
    benchmark : car
    task_name : MultiCarRacing-v1
    seed : 0
    height : 96
    width : 96
    frame_skip : 4
    pixel_norm : True
parameters :
    load : False
    dreamer :
        train_iterations : 20
        horizon_length : 15
        batch_size : 50
        batch_length : 50
        collect_interval : 1
        num_interaction_episodes : 1
        seed_episodes : 5
        num_evaluate : 3
        
        kl_divergence_scale : 1
        free_nats : 3
        discount : 0.99
        lambda_ : 0.95
        alpha : 0.1
        
        use_continue_flag : True
        actor_learning_rate : 0.0001
        critic_learning_rate : 0.0006
        model_learning_rate : 0.0006
        encoder_learning_rate : 0.0001
        discriminator_learning_rate : 0.001
        grad_norm_type : 2
        clip_grad : 100

        model_epsilon :  0.00000001
        actor_epsilon : 0.00001
        critic_epsilon : 0.00001
        
        deterministic_size : 200
        stochastic_size : 30
        embedded_state_size : 512
        buffer :
            capacity : 100000
        
        encoder : 
            depth : 32
            stride : 2
            kernel_size : 4
            activation : SiLU

        decoder : 
            depth : 32
            stride : 2
            kernel_size : 5
            activation : SiLU

        rssm :
            recurrent_model : 
                hidden_size : 500
                activation : SiLU

            transition_model : 
                hidden_size : 1000
                num_layers : 3
                activation : SiLU
                min_std : 0.1

            representation_model:
                hidden_size : 1000
                num_layers : 2
                activation : SiLU
                min_std : 0.1
            
        reward :
            hidden_size : 400
            num_layers : 3
            activation : SiLU

        continue_ :
            hidden_size : 400
            num_layers : 3
            activation : SiLU
        
        agent :
            actor :
                hidden_size : 400
                min_std : 0.1
                activation : SiLU
                num_layers : 4


            critic : 
                hidden_size : 400
                activation : SiLU
                num_layers : 3 
